version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=store_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 1234:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d store_db"]
      interval: 10s
      retries: 5
  db-test:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=store_db_test
    volumes:
      - ./data/db-test:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d store_db_test"]
      interval: 10s
      retries: 5
  web:
    build: .
    environment:
      - DB_URL=postgresql+psycopg2://admin:admin@db:5432/store_db
      - DB_TEST_URL=postgresql+psycopg2://admin:admin@db-test:5432/store_db_test
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000